version: '3.9'

services:
  webserver:
    container_name: nginx
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./subdomains.conf:/etc/nginx/conf.d/subdomains.conf
      - ./creds.ini:/root/creds.ini
      - ./cert/:/etc/letsencrypt/

networks:
  default:
    name: docker-net
